# Generated by Django 4.0 on 2022-01-01 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0002_stripecustomer'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripecustomer',
            name='cancel_at_period_end',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stripecustomer',
            name='membership',
            field=models.BooleanField(default=False),
        ),
    ]
